export type V3=[number,number,number];
export type Surface={points:V3[];color?:'blue'|'green'|'orange'|'gray';opacity?:number;outline?:boolean};
export type Stroke={points:V3[];color?:string;dashed?:boolean;width?:number};
export type Model={faces:Surface[];lines:Stroke[];labels:{point:V3;text:string}[];bounds?:V3[]};
export const add=(a:V3,b:V3):V3=>a.map((v,i)=>v+b[i]) as V3;
export const sub=(a:V3,b:V3):V3=>a.map((v,i)=>v-b[i]) as V3;
export const mul=(a:V3,n:number):V3=>a.map(v=>v*n) as V3;
export const dot=(a:V3,b:V3)=>a.reduce((s,v,i)=>s+v*b[i],0);
export const cross=(a:V3,b:V3):V3=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
export const length=(a:V3)=>Math.hypot(...a);
export function polygonArea(p:V3[]){let v:V3=[0,0,0];for(let i=1;i<p.length-1;i++)v=add(v,cross(sub(p[i],p[0]),sub(p[i+1],p[0])));return length(v)/2;}
export function circle(r:number,z:number,center:V3=[0,0,0],n=64):V3[]{return Array.from({length:n},(_,i)=>[center[0]+r*Math.cos(i*2*Math.PI/n),center[1]+r*Math.sin(i*2*Math.PI/n),center[2]+z] as V3);}
export function cubeFaces(a:number):V3[][]{return [[[0,0,0],[0,a,0],[a,a,0],[a,0,0]],[[0,0,a],[a,0,a],[a,a,a],[0,a,a]],[[0,0,0],[a,0,0],[a,0,a],[0,0,a]],[[a,a,0],[0,a,0],[0,a,a],[a,a,a]],[[0,a,0],[0,0,0],[0,0,a],[0,a,a]],[[a,0,0],[a,a,0],[a,a,a],[a,0,a]]];}
export function clipPolygon(poly:V3[],normal:V3,d:number,positive=true){const out:V3[]=[];const sign=positive?1:-1;for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],da=sign*(dot(a,normal)-d),db=sign*(dot(b,normal)-d);if(da>=-1e-9)out.push(a);if((da>1e-9&&db< -1e-9)||(da< -1e-9&&db>1e-9))out.push(add(a,mul(sub(b,a),da/(da-db))));}return out;}
export function cubeSection(t:number,a=2):V3[]{const points:V3[]=[];for(const face of cubeFaces(a))for(let i=0;i<4;i++){const u=face[i],v=face[(i+1)%4],d=dot(sub(v,u),[1,1,1]);if(!d)continue;const f=(t-dot(u,[1,1,1]))/d;if(f>=0&&f<=1){const p=add(u,mul(sub(v,u),f));if(!points.some(q=>length(sub(q,p))<1e-7))points.push(p);}}if(points.length<3)return points;const c=mul(points.reduce(add,[0,0,0]),1/points.length),u:V3=[1/Math.sqrt(2),-1/Math.sqrt(2),0],v:V3=[1/Math.sqrt(6),1/Math.sqrt(6),-2/Math.sqrt(6)];return points.sort((p,q)=>Math.atan2(dot(sub(p,c),v),dot(sub(p,c),u))-Math.atan2(dot(sub(q,c),v),dot(sub(q,c),u)));}
export function cubeSectionArea(t:number){if(t<0||t>6)return 0;if(t<=2)return Math.sqrt(3)*t*t/2;if(t<=4)return Math.sqrt(3)*(t*t-3*(t-2)**2)/2;return Math.sqrt(3)*(6-t)**2/2;}
export const cutArea=(c:number)=>96-(3-Math.sqrt(3))*c*c/2;
export const cylinderArea=(r:number)=>2*Math.PI*r*r+108*Math.PI/r;
const f=(n:number)=>Number(n.toFixed(2)).toString();
const pi=(n:number)=>`${f(n)}π`;
export type ExperimentSpec={label:string;unit:string;min:number;max:number;step:number;initial:number;start:string;end:string;description:string;focus?:{label:string;value:number};steps:[string,string][]};
export const specs:Record<number,ExperimentSpec>={
2:{label:'展开程度',unit:'%',min:0,max:100,step:1,initial:0,start:'合拢',end:'展开',description:'四个三角形绕底边打开，每个侧面的高始终为 5。',steps:[['找到斜高','底边中点到中心为 3，斜高 √(3²+4²)=5。'],['计算侧面积','每个三角形面积 ½×6×5=15，四个侧面共 60。'],['加上正方形底面','底面积 6²=36，表面积 60+36=96。']]},
3:{label:'展开程度',unit:'%',min:0,max:100,step:1,initial:0,start:'圆台',end:'扇环',description:'蓝色侧面展开为扇环。面积结果另外计入上、下底面。',steps:[['计算母线','母线 l=√(4²+(4−1)²)=5。'],['把曲面展开','侧面是两个扇形的面积差，S侧=π(R+r)l=25π。'],['加上两个底面','上底 π、下底 16π，表面积为 42π。']]},
4:{label:'沿棱切去的长度 c',unit:'cm',min:0,max:4,step:.01,initial:2,start:'不切',end:'切到相邻顶点',description:'蓝色保留，灰色小角移开，橙色是新增截面。',steps:[['减去旧表面','三个直角三角形总面积为 3c²/2。'],['加上新截面','新面是边长 c√2 的等边三角形，面积 √3 c²/2。'],['代入 c=2','96−6+2√3=90+2√3。这里 c 在 0–4 内。']]},
5:{label:'切面位置 t',unit:'',min:0,max:6,step:.01,initial:2,start:'一个顶点',end:'相对顶点',description:'切面始终满足 x+y+z=t，只平移，不改变方向。端点退化为点。',focus:{label:'定位最大截面',value:3},steps:[['观察形状变化','截面先是三角形，中段为六边形，再变回三角形。'],['利用对称性','t 与 6−t 的截面积相同；中心位置对应 t=3。'],['算中心正六边形','边长 √2，面积 6×(√3/4)×2=3√3。此最大值限于固定方向。']]},
6:{label:'切面到球心的距离 d',unit:'cm',min:0,max:5,step:.01,initial:3,start:'通过球心',end:'与球相切',description:'橙色为圆形截面，直角三角形把球半径、距离和截面半径连起来。',focus:{label:'切到球心',value:0},steps:[['画出直角三角形','球半径 5 为斜边，两直角边是 d 和截面半径 ρ。'],['求截面半径','ρ²=25−d²，截面积 S=π(25−d²)。'],['代入 d=3','ρ=4，截面积 16π；d=0 时最大，为 25π。']]},
7:{label:'切面距顶点 x',unit:'cm',min:0,max:8,step:.01,initial:4,start:'顶点',end:'底面',description:'切面保持平行于底面。线性尺寸缩半，面积缩为四分之一。',focus:{label:'切到高度的一半',value:4},steps:[['利用相似三角形','截面半径 ρ 与 x 的比值，等于底面半径与圆锥高的比值。'],['长度比例变成面积比例','ρ/4=x/8，所以 ρ=x/2，S=πx²/4。'],['代入 x=4','截面积为 4π，底面积为 16π，比例为 1/4。']]},
8:{label:'绕斜边旋转的角度',unit:'°',min:0,max:360,step:1,initial:0,start:'三角形',end:'旋转一周',description:'橙色三角形是当前生成面；两条直角边分别扫出上下圆锥的侧面。',focus:{label:'转满一周',value:360},steps:[['找到公共底面半径','斜边长 5，用三角形面积：½×3×4=½×5×ρ，得 ρ=12/5。'],['认出两个母线','两条直角边 3、4 分别成为两个圆锥的母线。'],['只加两个侧面积','π×(12/5)×3+π×(12/5)×4=84π/5；公共底面在内部。']]},
9:{label:'拆分观察距离',unit:'cm',min:0,max:4,step:.01,initial:0,start:'组合',end:'拆开观察',description:'抬起半球查看两个接触圆面；本题求两者合拢后的外表面积。',steps:[['保留圆柱外侧与下底','圆柱侧面积为 2π×3×4=24π，下底面积 9π。'],['保留半球曲面','半球曲面积为 2π×3²=18π。'],['去掉两个接触面','合拢后，圆柱上底与半球底面藏在内部，总面积 51π。']]},
10:{label:'圆柱半径 r',unit:'cm',min:1.5,max:5.5,step:.01,initial:2,start:'细高',end:'矮胖',description:'调整半径时，高度自动补偿，体积始终为 54π cm³。',focus:{label:'定位最省材料的尺寸',value:3},steps:[['用体积表示高度','πr²h=54π，所以 h=54/r²。'],['写出表面积函数','S(r)=2πr²+2πrh=2πr²+108π/r，r>0。'],['求导寻找最小值','S′=4πr−108π/r²=0，得 r=3；导数由负变正，h=6，S最小=54π。']]}
};
function wireCube(m:Model,a:number){for(const p of cubeFaces(a))m.lines.push({points:[...p,p[0]],color:'#7792a8',width:1});}
function shell(m:Model,r0:number,r1:number,z0:number,z1:number,color:Surface['color']='blue',opacity=1,n=64,angle=2*Math.PI){for(let i=0;i<n;i++){const a=angle*i/n,b=angle*(i+1)/n;m.faces.push({points:[[r0*Math.cos(a),r0*Math.sin(a),z0],[r0*Math.cos(b),r0*Math.sin(b),z0],[r1*Math.cos(b),r1*Math.sin(b),z1],[r1*Math.cos(a),r1*Math.sin(a),z1]],color,opacity,outline:false});}}
function hemisphere(m:Model,r:number,z:number,opacity=1){const n=40,k=12;for(let j=0;j<k;j++)for(let i=0;i<n;i++){const vertex=(jj:number,ii:number):V3=>{const a=jj*Math.PI/2/k,b=ii*2*Math.PI/n;return [r*Math.sin(a)*Math.cos(b),r*Math.sin(a)*Math.sin(b),z+r*Math.cos(a)];};m.faces.push({points:[vertex(j,i),vertex(j,i+1),vertex(j+1,i+1),vertex(j+1,i)],color:'blue',opacity,outline:false});}}
export function makeModel(id:number,v:number,gap=1):Model{
 const m:Model={faces:[],lines:[],labels:[]};
 if(id===2){const base:V3[]=[[-3,-3,0],[3,-3,0],[3,3,0],[-3,3,0]];m.faces.push({points:base,color:'green'});for(let i=0;i<4;i++){const a=base[i],b=base[(i+1)%4],mid=mul(add(a,b),.5),out=mul(mid,1/3),theta=Math.atan2(4,-3)*(1-v/100),tip=add(mid,add(mul(out,5*Math.cos(theta)),[0,0,5*Math.sin(theta)]));m.faces.push({points:[a,b,tip],color:'blue'});if(i===0){m.lines.push({points:[tip,mid],color:'#be6a31',width:2});m.labels.push({point:mul(add(tip,mid),.5),text:'斜高 5'});}}m.labels.push({point:[0,-3,0],text:'底边 6'});}
 if(id===3){const L=20/3,inner=5/3,s=.6+.4*v/100,c=Math.sqrt(Math.max(0,1-s*s)),n=100;const p=(rho:number,t:number):V3=>[rho*s*Math.sin(t*.6/s),rho*s*Math.cos(t*.6/s),(L-rho)*c];const outer:V3[]=[],inside:V3[]=[];for(let i=0;i<=n;i++){const t=-Math.PI+i*2*Math.PI/n;outer.push(p(L,t));inside.push(p(inner,t));}for(let i=0;i<n;i++)m.faces.push({points:[outer[i],outer[i+1],inside[i+1],inside[i]],color:'blue',outline:false});m.lines.push({points:outer,color:'#c97632',width:2.5},{points:inside,color:'#3d8978',width:2.5},{points:[outer[0],inside[0]],color:'#3269a4'},{points:[outer[n],inside[n]],color:'#3269a4'});m.labels.push({point:mul(add(outer[0],inside[0]),.5),text:'母线 5'});}
 if(id===4){const cap:V3[]=[[v,0,0],[0,v,0],[0,0,v]];for(const p of cubeFaces(4)){const q=clipPolygon(p,[1,1,1],v);if(q.length>=3)m.faces.push({points:q,color:'blue'});}if(v>0){m.faces.push({points:cap,color:'orange'});const shift:V3=[-gap,-gap,-gap];for(const p of cubeFaces(4)){const q=clipPolygon(p,[1,1,1],v,false);if(q.length>=3)m.faces.push({points:q.map(a=>add(a,shift)),color:'gray',opacity:.25});}m.faces.push({points:cap.map(a=>add(a,shift)),color:'gray',opacity:.15});m.labels.push({point:[v/3,v/3,v/3],text:'新增截面'});}m.bounds=[[-1.5,-1.5,-1.5],[4,4,4]];}
 if(id===5){for(const p of cubeFaces(2))m.faces.push({points:p,color:'blue',opacity:.05,outline:false});wireCube(m,2);const p=cubeSection(v);if(p.length>=3)m.faces.push({points:p,color:'orange',opacity:.85});m.labels.push({point:[1,1,2.35],text:`x+y+z = ${f(v)}`});m.bounds=[[0,0,0],[2,2,2.5]];}
 if(id===6){for(let j=1;j<12;j++){const z=5*Math.cos(j*Math.PI/12),r=5*Math.sin(j*Math.PI/12),p=circle(r,z);m.lines.push({points:[...p,p[0]],color:'#aec4d7',width:.75});}for(let k=0;k<12;k++){const a=k*Math.PI/12,p:V3[]=Array.from({length:65},(_,j)=>[5*Math.sin(j*Math.PI/32)*Math.cos(a),5*Math.sin(j*Math.PI/32)*Math.sin(a),5*Math.cos(j*Math.PI/32)]);m.lines.push({points:p,color:'#aec4d7',width:.75});}const rho=Math.sqrt(Math.max(0,25-v*v)),p=circle(rho,v);if(rho>0)m.faces.push({points:p,color:'orange',opacity:.9});m.lines.push({points:[[0,0,0],[0,0,v],[rho,0,v],[0,0,0]],color:'#3e6383',dashed:true,width:1.5});m.labels.push({point:[rho/2,0,v],text:`ρ = ${f(rho)}`},{point:[0,0,v/2],text:`d = ${f(v)}`});m.bounds=[[-5,-5,-5],[5,5,5]];}
 if(id===7){shell(m,4,0,0,8,'blue',.10);const rho=v/2,z=8-v;m.faces.push({points:circle(4,0),color:'green',opacity:.18});if(rho>0)m.faces.push({points:circle(rho,z),color:'orange',opacity:.9});m.lines.push({points:[[0,0,8],[4,0,0],[0,0,0],[0,0,8]],dashed:true,color:'#6b8a9d'},{points:[[0,0,z],[rho,0,z]],color:'#c47030',width:2});m.labels.push({point:[rho/2,0,z],text:`ρ = ${f(rho)}`},{point:[0,0,8-v/2],text:`x = ${f(v)}`});m.bounds=[[-4,-4,0],[4,4,8]];}
 if(id===8){const a=v*Math.PI/180,r=12/5,z=9/5,n=Math.max(1,Math.ceil(v/5));if(v>0){shell(m,0,r,0,z,'blue',.9,n,a);shell(m,r,0,z,5,'blue',.9,n,a);}const c:V3=[r*Math.cos(a),r*Math.sin(a),z];m.faces.push({points:[[0,0,0],[0,0,5],c],color:'orange',opacity:v===360?.15:.7});m.lines.push({points:[[0,0,0],[0,0,5]],color:'#587b99',dashed:true,width:1.5},{points:[[0,0,0],c,[0,0,5]],color:'#c36a2d',width:2});const ring=circle(r,z);m.lines.push({points:[...ring,ring[0]],color:'#7ca6a0',dashed:true});m.labels.push({point:mul(c,.5),text:'3'},{point:mul(add(c,[0,0,5]),.5),text:'4'},{point:[0,0,2.5],text:'旋转轴 · 5'});m.bounds=[[-r,-r,0],[r,r,5]];}
 if(id===9){shell(m,3,3,0,4);m.faces.push({points:circle(3,0),color:'green'});hemisphere(m,3,4+v);if(v>.005){m.faces.push({points:circle(3,4),color:'orange'},{points:circle(3,4+v),color:'green'});m.labels.push({point:[0,0,4+v/2],text:'接触面各 9π'});}m.bounds=[[-3,-3,0],[3,3,11]];}
 if(id===10){const h=54/(v*v);shell(m,v,v,0,h);m.faces.push({points:circle(v,0),color:'green'},{points:circle(v,h),color:'green'});m.lines.push({points:[[0,0,h],[v,0,h]],color:'#c47135',width:2});m.labels.push({point:[v,0,h/2],text:`h = ${f(h)}`},{point:[v/2,0,h],text:`r = ${f(v)}`});}
 return m;
}
export function metricsFor(id:number,v:number):{label:string;value:string;formula:string}[]{
 switch(id){case 2:return [{label:'四个侧面',value:'60',formula:'4 × ½ × 6 × 5'},{label:'底面积',value:'36',formula:'6²'},{label:'表面积',value:'96',formula:'60 + 36'}];case 3:return [{label:'侧面积',value:'25π',formula:'π(4+1)×5'},{label:'两个底面',value:'17π',formula:'π(1²+4²)'},{label:'表面积',value:'42π',formula:'25π + 17π'}];case 4:return [{label:'减少的旧表面',value:f(1.5*v*v),formula:'3c² / 2'},{label:'新增的截面',value:f(Math.sqrt(3)*v*v/2),formula:'√3 c² / 2'},{label:'剩余表面积',value:f(cutArea(v)),formula:'96 − 旧表面 + 新截面'}];case 5:return [{label:'当前截面积',value:f(cubeSectionArea(v)),formula:`t = ${f(v)}`},{label:'截面顶点数',value:String(cubeSection(v).length),formula:'端点时退化为点'},{label:'固定方向的最大值',value:'3√3',formula:'t = 3'}];case 6:return [{label:'截面半径',value:f(Math.sqrt(Math.max(0,25-v*v))),formula:'√(25−d²)'},{label:'当前截面积',value:pi(25-v*v),formula:'π(25−d²)'},{label:'最大截面积',value:'25π',formula:'d = 0'}];case 7:return [{label:'截面半径',value:f(v/2),formula:'x / 2'},{label:'当前截面积',value:pi(v*v/4),formula:'πx² / 4'},{label:'占底面积的比例',value:`${f(v*v/64*100)}%`,formula:'(x / 8)²'}];case 8:return [{label:'公共底面半径',value:'12/5',formula:'3×4 / 5'},{label:'已扫过的曲面面积',value:pi(16.8*v/360),formula:'(84π/5) × 角度/360°'},{label:'一周的外表面积',value:'84π/5',formula:'π × (12/5) × (3+4)'}];case 9:return [{label:'分开时总表面积',value:'69π',formula:'圆柱 42π + 半球 27π'},{label:'隐藏的接触面',value:'18π',formula:'2 × 9π'},{label:'合拢后的外表面积',value:'51π',formula:'69π − 18π'}];case 10:return [{label:'高度 h（cm）',value:f(54/(v*v)),formula:'54 / r²'},{label:'当前表面积',value:pi(cylinderArea(v)/Math.PI),formula:'2πr² + 108π/r'},{label:'最小表面积',value:'54π',formula:'r = 3，h = 6'}];default:return [];}
}
